name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup known_hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server
      run: |
        rsync -r --delete-after --quiet ${{ github.workspace }} sensai@45.136.71.121:/var/www/html
      env:
        DEPLOY_KEY: ${{ secrets.SENSEI_SSH }}
