name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server
      run: |
        rsync -r --delete-after --quiet ${{ github.workspace }} sensai@45.136.71.121:/var/www/html
      env:
        DEPLOY_KEY: ${{ secrets.sensai_ssh }}
